"""first

Revision ID: 97f7e53201b2
Revises: 
Create Date: 2022-09-19 18:31:40.419891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f7e53201b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.REAL(), nullable=False),
    sa.Column('currency_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('USD_relative_value', sa.REAL(), nullable=False),
    sa.Column('available_quantity', sa.REAL(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_date', sa.String(length=20), nullable=False),
    sa.Column('closing_date', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.REAL(), nullable=False),
    sa.Column('interest_rate', sa.REAL(), nullable=False),
    sa.Column('dividends_account', sa.String(length=20), nullable=False),
    sa.Column('dividends_date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_initial', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=60), nullable=True),
    sa.Column('currency_num_spent', sa.REAL(), nullable=True),
    sa.Column('currency_num_obtained', sa.REAL(), nullable=True),
    sa.Column('currency_name_spent', sa.String(length=20), nullable=True),
    sa.Column('currency_name_obtained', sa.String(length=20), nullable=True),
    sa.Column('date_time', sa.String(length=20), nullable=True),
    sa.Column('user_id_final', sa.Integer(), nullable=True),
    sa.Column('commission', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('rating')
    op.drop_table('deposit')
    op.drop_table('currency')
    op.drop_table('account')
    # ### end Alembic commands ###
